KeyifliBilet/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KeyifliBilet.Models
{
    public class Search
    {
        public bool IsOneWay { get; set; }
        public string DEP_Airport_Code { get; set; }
        public string DEP_Airport_Name { get; set; }
        public string DEP_Airport_CityName { get; set; }
        public bool DEP_Airport_IsCity { get; set; } // allinFromCity
        public string DepartureDate { get; set; }
        public string ARR_Airport_Code { get; set; }
        public string ARR_Airport_Name { get; set; }
        public string ARR_Airport_CityName { get; set; }
        public bool ARR_Airport_IsCity { get; set; }
        public string ReturnDate { get; set; }
        public int Adult { get; set; }
        public int Child { get; set; }
        public int Infant { get; set; }
        public int Total { get; set; }
        public string CabinClass { get; set; }
        public bool NoStop { get; set; }
    }
}

KeyifliBilet/Controllers/HomeController.cs
using KeyifliBilet.Areas.Yonetim.Models;
using KeyifliBilet.Iati.Request;
using KeyifliBilet.Iati.Response;
using KeyifliBilet.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Cors;
using System.Web.ModelBinding;
using System.Web.Mvc;

namespace KeyifliBilet.Controllers
{

    public class HomeController : Controller
    {
        static List<string> result;
        IndexViewModel vm = new IndexViewModel();
        KeyifliBiletEntities entities = new KeyifliBiletEntities();


        public PartialViewResult HeaderIndex()
        {

            return PartialView();
        }

        [HttpPost]
        public ActionResult KayitOl(FormCollection data)
        {
            var mail = data["txtReqEmail"];
            var gsm = data["txtReqMobile"];
            int uyeCon = entities.Uyeler.Where(w => w.Mail == mail && w.GSM == gsm).Count();
            if (uyeCon == 0)
            {
                Uyeler uye = new Uyeler();
                uye.AdSoyad = data["Name"] + " " + data["Surname"];
                uye.Durum = false;
                uye.GSM = data["txtReqMobile"];
                uye.KampanyaDurum = true;
                uye.KayitTarihi = DateTime.Now;
                uye.Mail = data["txtReqEmail"];
                uye.Sifre = data["Password"];
                entities.Uyeler.Add(uye);
                entities.SaveChanges();

                var user = entities.Uyeler.Where(w => w.Mail == mail).First();
                System.Net.Mail.MailMessage m = new System.Net.Mail.MailMessage(
                                            new System.Net.Mail.MailAddress("oget.metin@gmail.com", "Keyifli Bilet Kayıt Maili"),
                                            new System.Net.Mail.MailAddress(mail));


                m.Subject = "Email onaylama";
                m.Body = string.Format("Sayın {0}<BR/>Kayıt olduğunuz için teşekkürler, lütfen kaydınızı doğrulamak için adrese tıklayınız: <a href=\"{1}\" title=\"Kullanıcı E-mail Doğrulama\">{1}</a>", uye.Mail, Url.Action("Index", "Home", new { Token = user.UyeId, Email = user.Mail }, Request.Url.Scheme));
                m.IsBodyHtml = true;
                System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
                smtp.Credentials = new System.Net.NetworkCredential("oget.metin@gmail.com", "Rizgar1341?");
                smtp.EnableSsl = true;
                smtp.Send(m);
            }
            else
            {
                //Üye Zaten Kayıtlı
            }


            return RedirectToAction("Index", "Home");

        }

        public ActionResult Cikis()
        {
            Session["UyeId"] = null;

            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
        public class Order
        {
            public string Tk { get; set; }
            public string Ad { get; set; }
            public string Soyad { get; set; }
            public string Kalkis { get; set; }
            public string Varis { get; set; }
            public string Tarih { get; set; }
            public string Saat { get; set; }
            public string Sinif { get; set; }
            public string Ucret { get; set; }
        }
        [HttpPost]
        public async Task<ActionResult> PnrSorgulama(FormCollection data)
        {
            var pnr = data["pnr"];
            var soyad = data["soyad"];

            var pnrId = entities.BookingInfo.Where(w => w.pnr == pnr.ToUpper()).FirstOrDefault();
            var Id = entities.BookingInfo.Where(w => w.pnr == pnr.ToUpper()).FirstOrDefault().Id;
            var trrr = entities.OrderResult.FirstOrDefault(w => w.Id == Id).orderId;
            var yolcu = entities.passengers.Where(w => w.surname.ToUpper() == soyad.ToUpper() && w.Id == Id).FirstOrDefault();

            GetOrderResponse order = null;
            if (yolcu != null)
            {
                order = await Iati.Search.GetOrder(new GetOrderRequest { orderId = Convert.ToInt32(trrr) });
            }
            else
            {
                order = null;
                //pnr ve ya soyadını kontrol ediniz.
            }

            return View(order);
        }

        [HttpPost]
        public ActionResult Giris(FormCollection data)
        {
            var mail = data["txtLogEmail"];
            var sifre = data["txtLogPassword"];
            var login = entities.Uyeler.Where(m => m.Mail == mail).FirstOrDefault();
            if (login != null)
            {
                if (login.Mail == mail && login.Sifre == sifre && login.Durum == true)
                {
                    Session["UyeId"] = login.UyeId;
                    Session["AdSoyad"] = login.AdSoyad;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Uyari = "Kullanıcı Adı veya Şifreyi Kontrol Ediniz / Yeni Kayıt Olduysanız ONAY Verilmesini Beklemelisiniz!";
                    return RedirectToAction("Index", "Home");

                }
            }
            else
            {
                ViewBag.Uyari = "Kullanıcı Adı veya Şifreyi Kontrol Ediniz / Yeni Kayıt Olduysanız ONAY Verilmesini Beklemelisiniz!";
                return RedirectToAction("Index", "Home");

            }

        }

        [HttpPost]
        public ActionResult BizeUlasin(FormCollection data)
        {
            IletisimFormu ulas = new IletisimFormu();
            ulas.AdSoyad = data["NameSurname"];
            ulas.Mail = data["Email"];
            ulas.Telefon = data["Mobile"];
            ulas.Mesaj = data["Message"];
            ulas.Durum = false;
            ulas.OkunmaTarihi = null;
            ulas.Tarih = DateTime.Now;
            entities.IletisimFormu.Add(ulas);
            entities.SaveChanges();
            return View("Index");
        }

        public ActionResult Biletlerim()
        {
            int sesion = Convert.ToInt32(Session["UyeId"]);

            vm.uyeler = entities.Uyeler.Where(w => w.UyeId == sesion);
            var data = entities.OrderResult.FirstOrDefault(w => w.UyeId == sesion).Id;
            vm.leg = entities.legs.Where(w => w.Id == data).ToList();

            return View(vm);
        }

        public ActionResult Profil()
        {
            int sesion = Convert.ToInt32(Session["UyeId"]);
            vm.uyeler = entities.Uyeler.Where(w => w.UyeId == sesion).ToList();
            return View(vm);
        }
        [HttpPost]
        public ActionResult Profil(FormCollection data)
        {
            var sifre = data["mevcut"];
            int UyeId = Convert.ToInt32(Session["UyeId"]);
            var uyeId = entities.Uyeler.Where(w => w.UyeId == UyeId).FirstOrDefault();
            if (sifre!=null)
            {
                string t = entities.Uyeler.Where(w => w.UyeId == UyeId).FirstOrDefault().Sifre;
                if (t==sifre)
                {
                    uyeId.Sifre = data["yeni"];
                    entities.SaveChanges();
                }
            }
            else
            {
                
                uyeId.AdSoyad = data["txtUpName"];
                uyeId.GSM = data["txtUpMobile"];
                uyeId.Mail = data["txtUpEmail"];
                entities.SaveChanges();
            }
          
            return View(vm);
        }


        [HttpPost]
        public ActionResult SifremiUnuttum(FormCollection form)
        {
            string mail = form["Email"].Trim();
            var data = entities.Uyeler.Where(w => w.Mail == mail).First();
            System.Net.Mail.MailMessage m = new System.Net.Mail.MailMessage(
                  new System.Net.Mail.MailAddress("oget.metin@gmail.com", "Şifreniz ve Kullanıcı Adınız"),
                  new System.Net.Mail.MailAddress(data.Mail));


            m.Subject = "Email onaylama";
            m.Body = string.Format(" Kullanıcı Adınız : {0}<BR/> Şifreniz : {1}<BR/> ", data.Mail, data.Sifre);
            m.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential("oget.metin@gmail.com", "Rizgar1341?");
            smtp.EnableSsl = true;
            smtp.Send(m);
            return RedirectToAction("Index", "Home");
        }


        public PartialViewResult Slider()
        {
            return PartialView();
        }
        public PartialViewResult PartialSearch()
        {
            var model = new ViewSearch();
            return PartialView(model);
        }
        public PartialViewResult PartialSearchWithModel(ViewSearch model)
        {

            return PartialView(model);
        }
        [HttpPost]
        public async Task<JsonResult> Calendar(ViewSearch model)
        {
            var cal = new GetCalendarRequest();
            if (Convert.ToDateTime(model.DepartureDate).DayOfYear - DateTime.Now.DayOfYear >= 3)
            {
                cal.departureDateTimeBegin = Convert.ToDateTime(model.DepartureDate).AddDays(-4).ToString("yyyy-MM-dd");
                cal.departureDateTimeEnd = Convert.ToDateTime(model.DepartureDate).AddDays(3).ToString("yyyy-MM-dd");
                cal.returnDateTimeBegin = model.ReturnDate != null ? Convert.ToDateTime(model.ReturnDate).AddDays(-4).ToString("yyyy-MM-dd") : "";
                cal.returnDateTimeEnd = model.ReturnDate != null ? Convert.ToDateTime(model.ReturnDate).AddDays(3).ToString("yyyy-MM-dd") : "";
                cal.currency = "TL";
                cal.routes = new List<GetCalendar>() {
                    new GetCalendar(){
                        fromAirportCode =model.DEP_Airport_Code,

KeyifliBilet/Controllers/trController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KeyifliBilet.Controllers
{
    public class trController : Controller
    {
        [Route("tr/iptal-iade",Name ="iptaliade")]
        public ActionResult IptalIade()
        {
            return View();
        }

        [Route("tr/online-check-in",Name ="onlinecheckin")]
        public ActionResult OnlineCheckIn()
        {
            return View();
        }
        [Route("tr/iletisim",Name ="iletisim")]
        public ActionResult Iletisim()
        {
            return View();
        }
    }
}

KeyifliBilet/Views/Home/Biletlerim.cshtml
@model KeyifliBilet.Areas.Yonetim.Models.IndexViewModel
@{
    ViewBag.Title = "Biletlerim";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@Html.Action("HeaderIndex", "Home")
<section class="mt-sm-5 mt-5">
    <div class="container mt-sm-5">
        <div class="heading-title heading-border">
            <h1 class="text-black">Biletlerim</h1>
        </div>
       
        <div class="panel panel-default">
            <div class="panel-body">
                <ul class="nav nav-tabs">
                    <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#futureFlight">Geçmiş Uçuşlarım</a></li>
                  
                    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#pastFlight">Gelecek Uçuşlarım</a></li>

                </ul>
                <div class="tab-content">
                    <div class="tab-pane container active" id="futureFlight">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Havayolu</th>
                                    <th>Kalkış</th>
                                    <th>Varış</th>
                                    <th>Tarih</th>
                                    <th>Sınıf</th>
                                    <th>Fiyat</th>
                                </tr>
                                @if (Model.leg != null)
                                {

                                    foreach (var item in Model.leg)
                                    {
                                        if (item.arrivalTime < DateTime.Now)
                                        {
                                            <tr>
                                                <td>@item.departureAirportName</td>
                                                <td>@item.localDepartureDate</td>
                                                <td>@item.localDepartureDate</td>
                                                <td>@item.departureTime</td>
                                                <td>@Model.passenger.FirstOrDefault().totalPrice</td>
                                            </tr>
                                        }
                                    }
                                }

                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="tab-pane container fade" id="pastFlight">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Havayolu</th>
                                    <th>Kalkış</th>
                                    <th>Varış</th>
                                    <th>Tarih</th>
                                    <th>Sınıf</th>
                                    <th>Fiyat</th>
                                </tr>
                               
                                @if (Model.leg != null)
                                {

                                    foreach (var item in Model.leg)
                                    {
                                        if (item.arrivalTime > DateTime.Now)
                                        {
                                            <tr>
                                                <td>@item.departureAirportName</td>
                                                <td>@item.localDepartureDate</td>
                                                <td>@item.localDepartureDate</td>
                                                <td>@item.departureTime</td>
                                               <td></td>
                                            </tr>
                                        }
                                    }
                                }
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Action("Footer", "Home")
@Html.Action("PartialSignUp", "Home")

KeyifliBilet/Views/Home/Blog.cshtml
<section class="section hidden-xs thumbnail-contents">
    <div class="container">
        <div class="text-center">
            <h2>Son Eklenen Seyahat Yazıları</h2>
        </div>
        <div class="row grid">
            <div class="col-sm-4 text-center grid-bottom pl-20 pr-20">
                <img src="/Uploaded/Media_Content_dd249e4c-b0ee-4681-996d-a46889c32d71X.jpg" class="img-rounded grid-bottom max-width-100">
                <h4>Uzun aktarmalarda yapılabilecek 6 şey</h4>
                <p>Bağlantılı uçuşlar arasında bekleme süresi olarak da bilinen aktarmaların fazla uzun sürmesi pek istenen bir durum sayılmaz.</p>
                <br>
                <a href="https://www.keyiflibilet.com/tr/blog/uzun-aktarmalarda-yapilabilecek-6-sey" class="bold">Detaylı bilgi<span class="fa fa-angle-double-right red"></span></a>
            </div>
            <div class="col-sm-4 text-center grid-bottom pl-20 pr-20">
                <img src="/Uploaded/Media_Content_a5299e0c-f58c-4258-8238-b6c111f1be81X.jpg" class="img-rounded grid-bottom max-width-100">
                <h4>El bagajına alınabilecekler ve alınamayacaklar</h4>
                <p>Özellikle uçağa biniş ve iniş sırasında zaman kazandıran el bagajı birkaç günlük kısa tatillerde tam bir hayat kurtarıcı olabiliyor. </p>
                <br>
                <a href="https://www.keyiflibilet.com/tr/blog/el-bagajina-alinabilecekler-ve-alinamayacaklar" class="bold">Detaylı bilgi<span class="fa fa-angle-double-right red"></span></a>
            </div>
            <div class="col-sm-4 text-center grid-bottom pl-20 pr-20">
                <img src="/Uploaded/Media_Content_e1e9ca6d-6c12-406e-bb24-991fabaf1cdfX.jpg" class="img-rounded grid-bottom max-width-100">
                <h4>Uçus öncesinde dikkat edilecek kurallar</h4>
                <p>Uçağa binmeden önce ve uçakta her yolcunun uyması gereken bazı kurallar vardır. Bu kuralların uygulanması güvenlik açısından gerekmektedir</p>
                <br>
                <a href="https://www.keyiflibilet.com/tr/blog/ucus-oncesinde-dikkat-edilecek-kurallar" class="bold">Detaylı bilgi<span class="fa fa-angle-double-right red"></span></a>
            </div>
        </div>
    </div>
</section>

KeyifliBilet/Views/Home/FlightImages.cshtml
<section class="padding-xxs">
    <div class="container">
        <div class="text-center">
            <h2 class="nomargin">Yüzlerce Havayolunun Uçak Biletleri</h2>
            <div class="flight-slider nomargin">
                <div class="item">
                    <img src="/Uploaded/1674-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1279-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1639-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1268-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1573-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1518-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1170-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1173-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1196-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1303-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1624-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1702-md.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1589-md-1.png">
                </div>
                <div class="item">
                    <img src="/Uploaded/1163-md.png">
                </div>

            </div>
        </div>
    </div>
</section>

KeyifliBilet/Views/Home/HeaderIndex.cshtml
@if (Session["UyeId"] == null)
{
    <header class="cd-header">
        <div id="cd-logo"><a href="@Url.Action("Index","Home")"><img src="~/Content/assets/images/logo.png" alt="Adaş Turizm"></a></div>


        <nav class="cd-main-nav">
            <ul>
                <li><a href="@Url.Action("IptalIade","tr")">İptal / İade</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("OnlineCheckIn","tr")">Online Check-In</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("iletisim","tr")">İletişim</a></li>
                <li class="right dropdown">
                    <a class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">TR</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="https://www.keyiflibilet.com/#">EN</a>
                    </div>
                </li>
                <li class="right"><a href="https://www.keyiflibilet.com/#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="login" class="btnMember"><i class="icon-user"></i> Giriş Yap</a></li>
                <li class="divider right"></li>
                <li class="right"><a href="https://www.keyiflibilet.com/#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="register" class="btnMember">Üye Ol</a></li>
                <li class="divider right"></li>
                <li class="right phone"><a href="@Url.Action("iletisim","tr")"><i class="icon-phone3"></i> 0850 550 41 14</a></li>
            </ul>
        </nav>

        <a href="https://www.keyiflibilet.com/#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="login" class="btnMember visible-xs"><i class="icon-user"></i> Giriş Yap</a>
    </header>

}
else
{
    <header class="cd-header">
        <div id="cd-logo"><a href="@Url.Action("Index","Home")"><img src="~/Content/assets/images/logo.png" alt="Adaş Turizm"></a></div>

        <nav class="cd-main-nav">
            <ul>
                <li><a href="@Url.Action("IptalIade","tr")">İptal / İade</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("OnlineCheckIn","tr")">Online Check In</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("iletisim","tr")">İletişim</a></li>



                <li class="right hidden-xs">
                    <a class="dropdown-toggle no-text-underline" data-toggle="dropdown" href="#"><i class="flaticon-people"></i> <span class="hidden-xs">@Session["AdSoyad"]</span></a>
                    <ul class="dropdown-menu pull-right">
                        <li><a tabindex="-1" href="@Url.Action("Biletlerim","Home")">Biletlerim</a></li>
                        <li class="divider"></li>
                        <li><a tabindex="-1" href="@Url.Action("Profil","Home")">Profil Ayarlar</a></li>
                        <li class="divider"></li>
                        <li><a tabindex="-1" href="@Url.Action("Cikis","Home")">Güvenli Çıkış</a></li>
                    </ul>
                </li>


            </ul>
        </nav>
        <a href="https://www.keyiflibilet.com/#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="login" class="btnMember visible-xs"><i class="icon-user"></i> Giriş Yap</a>
    </header>
}

KeyifliBilet/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}

@Html.Action("HeaderIndex", "Home")
<section id="adas-home">
    @Html.Action("Slider", "Home")
    <div id="adas-home-tagline-sticky-wrapper" class="sticky-wrapper" style="height: 334px;">
        <div id="adas-home-tagline" style="width: 1539px;">
            <div class="container">
                <div class="search-engine">
                    <ul class="nav search-engine-main-nav justify-content-center" id="pills-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="flight-tab" data-toggle="tab" href="#tabQuickFlights" role="tab" aria-controls="tabQuickFlights" aria-selected="true">Uçuş Ara / Bilet Al</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pnr-tab" data-toggle="tab" href="#tabQuickPNR" role="tab" aria-controls="tabQuickPNR" aria-selected="false">PNR Sorgulama</a>
                        </li>
                    </ul>
                    <div class="search-engine-steps tab-content" id="pills-tabContent">
                        @Html.Action("PartialSearch", "Home")
                        @Html.Action("PartialPNR", "Home")
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<div id="yourContainer"></div>
@Html.Action("Blog", "Home")   
@Html.Action("Features", "Home")
@Html.Action("SignUp", "Home")
@Html.Action("FlightImages", "Home")
@Html.Action("Footer", "Home")
@Html.Action("PartialSignUp", "Home")
@section js{
    <script src="~/Content/assets/js/scripts.js"></script>
    <script src="~/Content/assets/plugins/bootstrap.daterangepicker/moment.min.js"></script>
    <script src="~/Content/assets/plugins/bootstrap.daterangepicker/daterangepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#yourContainer").load('@Url.Action("PartialDestenation", "Home")')
            //$("#adas-home-tagline").sticky({ topSpacing: 0 });
            //$('#layerslider').layerSlider({ skin: 'noskin', skinsPath: 'Content/assets/plugins/slider.layerslider/skins/', pauseOnHover: false, navButtons: true, slideDirection: 'top' });
            //WDT.SearchBox.CreateBox();
            //WDT.SearchPnr.Init();
            //WDT.Member.LoginRequired();
        });</script>
    <script type="text/javascript">
        $(document).ready(function () {
            //WDT.Member.Init();
        });
    </script>
}

KeyifliBilet/Views/Home/PartialPNR.cshtml
<div class="engine-step tab-pane" id="tabQuickPNR" role="tabpanel" aria-labelledby="pnr-tab">


    <form action="@Url.Action("PnrSorgulama","Home")" id="frmSearchPnr" method="post" novalidate="novalidate">
        <div class="row">
            <div class="col-md-5 tabs-type-a tabs-block">
                <button class="btn btn-secondary btn-lg dropdown-toggle custom-input animated flipInX" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <input autocomplete="off" data-val="true" data-val-required="Lütfen yolcunun soyismini giriniz !" id="Surname" name="Surname" placeholder="Yolcunun Soyismi" style="text-transform:uppercase" type="text" value="">
                </button>
                <span class="field-validation-valid" data-valmsg-for="Surname" data-valmsg-replace="true"></span>
            </div>
            <div class="col-md-5 tabs-type-a tabs-block">
                <button class="btn btn-secondary btn-lg dropdown-toggle custom-input animated flipInX" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <input autocomplete="off" data-val="true" data-val-required="Lütfen pnr numrasını giriniz !" id="PNR" name="PNR" placeholder="Bilet kodu (PNR)" style="text-transform:uppercase" type="text" value="">
                </button>
                <span class="field-validation-valid" data-valmsg-for="PNR" data-valmsg-replace="true"></span>
            </div>
            <div class="col-md-2 text-right">
                <button type="submit" class="srch-btn animated flipInX"><i class="icon-angle-right"></i></button>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 mt-10">
                <div class="pull-left hidden-desktop">
                    <a class="text-white" href="#yardim">Rezervasyon kodu (PNR) ve bilet numarası nedir?</a>
                </div>
            </div>
        </div>
    </form>
</div>

KeyifliBilet/Views/Home/PnrSorgulama.cshtml
@model KeyifliBilet.Iati.Response.GetOrderResponse
@{
    ViewBag.Title = "PnrSorgulama";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@Html.Action("HeaderIndex", "Home")
@if (Model.result!=null)
{
    <section class="mt-sm-5 mt-5">
        <div class="container mt-sm-5">
            @{var test=Model.result.cancellationInfo.pnr}
            <div class="heading-title heading-border">
                <h1 class="text-black">PNR :  @test</h1>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Bilet No</th>
                                <th>İsim Soyisim</th>
                                <th>Kalkış</th>
                                <th>Varış</th>
                                <th>Tarih Saat</th>
                                <th>Sınıf</th>
                                <th>Fiyat</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.result.legs)
                            {
                                foreach (var data in Model.result.passengers)
                                {
                            <tr>

                                <td>@data.eticket</td>
                                <td>@data.name @data.surname </td>
                                <td>@item.departureAirport, @item.departureCityName (@item.departureCityCode) </td>
                                <td>@item.arrivalAirport, @item.arrivalCityName (@item.arrivalCityCode) </td>
                                <td>@item.departureTime.ToShortDateString() @item.departureTime.ToShortTimeString()</td>
                                <td>@item.classCode</td>
                                <td>@data.totalPrice TL </td>
                            </tr>
                                }

                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </section>
}

else
{
    <div class="heading-title heading-border">

        <h1 class="text-black">Arama kriterlerinize uygun PNR bilgisi bulunamadı</h1>
    </div>
}
@Html.Action("Footer", "Home")
@Html.Action("PartialSignUp", "Home")

KeyifliBilet/Views/Home/Search.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}

<h2>Search</h2>