KeyifliBilet/Areas/Yonetim/Models/IletisimFormu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IletisimFormu
    {
        public int IletisimId { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Mesaj { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> OkunmaTarihi { get; set; }
    }
}

KeyifliBilet/Areas/Yonetim/Models/MailKategori.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MailKategori()
        {
            this.Mailler = new HashSet<Mailler>();
        }
    
        public int MailKategoriId { get; set; }
        public string Aciklama { get; set; }
        public string Kod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mailler> Mailler { get; set; }
    }
}

KeyifliBilet/Areas/Yonetim/Models/Siniflar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public int SinifId { get; set; }
        public string SinifAdi { get; set; }
        public Nullable<decimal> ServisBedeli { get; set; }
    }
}

KeyifliBilet/Areas/Yonetim/Models/SmsKategori.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmsKategori()
        {
            this.Sms = new HashSet<Sms>();
        }
    
        public int SmsKategoriId { get; set; }
        public string Aciklama { get; set; }
        public string Kod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sms> Sms { get; set; }
    }
}

KeyifliBilet/Areas/Yonetim/Models/SosyalMedya.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SosyalMedya
    {
        public int Id { get; set; }
        public string Platform { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}

KeyifliBilet/Areas/Yonetim/Models/Uyeler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.OrderResult = new HashSet<OrderResult>();
        }
    
        public int UyeId { get; set; }
        public string Mail { get; set; }
        public string GSM { get; set; }
        public string Sifre { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<bool> KampanyaDurum { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderResult> OrderResult { get; set; }
    }
}

KeyifliBilet/Areas/Yonetim/Controllers/PanelController.cs
using KeyifliBilet.Areas.Yonetim.Models;
using KeyifliBilet.Iati.Enums;
using KeyifliBilet.Iati.Request;
using KeyifliBilet.Iati.Response;
using KeyifliBilet.Models;
using KeyifliBiletPanel.Extensions;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using static KeyifliBilet.Areas.Yonetim.Controllers.PanelController.Enum;

namespace KeyifliBilet.Areas.Yonetim.Controllers
{

    public class PanelController : Controller
    {
        IndexViewModel vm = new IndexViewModel();
        KeyifliBiletEntities entities = new KeyifliBiletEntities();
        public static int id = 0;
        // GET: Panel
        [MyFilterAdmin]
        [KullaniciYetkiler(Roles = "Anasayfa")]
        public async System.Threading.Tasks.Task<ActionResult> Index()
        {
            var res = await Iati.Search.GetBalanceSummary();
            var uye = entities.Uyeler.Count();
            var bilet = entities.BookingInfo.Count();
            var kutu = entities.Kutu.Count();
            ViewBag.balance = res.result.balance.ToString() + " " + res.result.currency;
            ViewBag.uye = uye;
            ViewBag.bilet = bilet;
            ViewBag.kutu = kutu;
            return View();
        }

        public PartialViewResult UserName()
        {
            if (id == 0)
            {
                vm.uyeler = entities.Uyeler.Where(w => w.UyeId == id);
            }

            return PartialView(vm);
        }
        [MyFilterAdmin]
        [KullaniciYetkiler(Roles = "Profil")]
        public ActionResult Profil()
        {
            int rolId = 0;
            var data = entities.Rol.Where(w => w.KullaniciId == id).FirstOrDefault();
            rolId = data.RolId;
            vm.kullanicilar = entities.Kullanicilar.Where(w => w.KullaniciId == id);
            vm.rol = entities.Rol.Where(w => w.KullaniciId == id);
            vm.yetki = entities.Yetki.Where(w => w.RolId == rolId).ToList();
            return View(vm);
        }

        #region ÜYELER
        [MyFilterAdmin]
        [KullaniciYetkiler(Roles = "Uyeler")]
        public ActionResult Uyeler()
        {
            vm.uyeler = entities.Uyeler.ToList();
            return View(vm);
        }

        [MyFilterAdmin]
        [KullaniciYetkiler(Roles = "UyeDurum")]
        public ActionResult UyeAktifPasif(int? id)
        {
            var uye = entities.Uyeler.Where(w => w.UyeId == id).FirstOrDefault();
            if (uye.Durum == true)
            {
                uye.Durum = false;
            }
            else
            {
                uye.Durum = true;

            }
            entities.SaveChanges();
            return RedirectToAction("Uyeler");
        }

        [MyFilterAdmin]
        [KullaniciYetkiler(Roles = "KampanyaDurum")]
        public ActionResult KampanyaDurum(int? id)
        {
            var uye = entities.Uyeler.Where(w => w.UyeId == id).FirstOrDefault();
            if (uye.KampanyaDurum == true)
            {
                uye.KampanyaDurum = false;

            }
            else
            {
                uye.KampanyaDurum = true;

            }
            entities.SaveChanges();
            return RedirectToAction("Uyeler");
        }

        [MyFilterAdmin]
        [HttpGet]
        [KullaniciYetkiler(Roles = "UyeGuncelleme")]
        public PartialViewResult UyeGuncelle(int UyeId)
        {

            vm.uyeler = entities.Uyeler.Where(w => w.UyeId == UyeId);
            return PartialView(vm);

        }

        [MyFilterAdmin]
        [HttpPost]
        [KullaniciYetkiler(Roles = "UyeGuncelleme")]
        public ActionResult UyeGuncelle(FormCollection data, int? uyeId)
        {
            var uye = entities.Uyeler.Where(w => w.UyeId == uyeId).FirstOrDefault();
            var durum = entities.Uyeler.Where(w => w.UyeId == uyeId).FirstOrDefault().Durum;
            var kampanya = entities.Uyeler.Where(w => w.UyeId == uyeId).FirstOrDefault().KampanyaDurum;
            var sifre = entities.Uyeler.Where(w => w.UyeId == uyeId).FirstOrDefault().Sifre;
            var kayit = entities.Uyeler.Where(w => w.UyeId == uyeId).FirstOrDefault().KayitTarihi;

            uye.AdSoyad = data["adsoyad"];
            uye.Mail = data["mail"];
            uye.GSM = data["telefon"];
            uye.KayitTarihi = kayit;
            uye.Durum = durum;
            uye.KampanyaDurum = kampanya;
            uye.Sifre = sifre;
            entities.SaveChanges();
            vm.uyeler = entities.Uyeler.ToList();

            return View("Uyeler", vm);
        }

        #endregion
        public abstract class BaseController : Controller
        {

            public void Alert(string message, NotificationType notificationType)
            {
                var msg = "swal('" + notificationType.ToString().ToUpper() + "', '" + message + "','" + notificationType + "')" + "";
                TempData["notification"] = msg;
            }
        }
        public class Enum
        {
            public enum NotificationType
            {
                error,
                success,
                warning,
                info
            }

        }
        #region EKSTRA SERVİS BEDELİ
        [MyFilterAdmin]
        [KullaniciYetkiler(Roles = "EkstraServisBedeli")]
        public ActionResult EkstraServisBedeli()
        {
            vm.ekstraServis = entities.EkstraServis.ToList();
            return View(vm);
        }

        [MyFilterAdmin]
        [HttpGet]
        [KullaniciYetkiler(Roles = "EkstraServisBedeliEkle")]
        public PartialViewResult ServisEkle()
        {
            return PartialView();
        }
        [HttpPost]
        [KullaniciYetkiler(Roles = "EkstraServisBedeliEkle")]
        public PartialViewResult ServisEkle(FormCollection data)
        {
            EkstraServis servis = new EkstraServis();
            string kalkisYeri = data["kalkisYeri"];
            string varisYeri = data["varisYeri"];
            string[] kalkis = kalkisYeri.Split('-');
            string[] varis = varisYeri.Split('-');



            if (data["myCheck"] != null)
            {
                // 1.Ekstra Servis Bedeli eklenecek
                servis.BaslangicTarihi = Convert.ToDateTime(data["baslangicTarihi"]);
                servis.BitisTarihi = Convert.ToDateTime(data["bitisTarihi"]);
                servis.DonusEklensinMi = true;
                servis.KalkisKod = kalkis[0];
                servis.KalkisHavalimani = kalkis[1];
                servis.KalkisSehir = kalkis[2];
                servis.KalkisUlke = kalkis[3];

                servis.KoltukLimiti = Convert.ToInt32(data["koltukLimiti"]);
                servis.LimiteBagliServisBedeli = Convert.ToDecimal(data["limiteBagliServis"]);
                servis.ServisBedeli = Convert.ToDecimal(data["ekstraServisBedeli"]);
                servis.Durum = true;
                if (data["tip"] == "İÇ HAT")
                {
                    servis.Tip = true;
                }
                else
                {
                    servis.Tip = false;
                }
                servis.VarisKod = varis[0];
                servis.VarisHavalimani = varis[1];
                servis.VarisSehir = varis[2];
                servis.VarisUlke = varis[3];
                entities.EkstraServis.Add(servis);
                entities.SaveChanges();
                // 2.Ekstra Servis Bedeli eklenecek
                servis.BaslangicTarihi = Convert.ToDateTime(data["baslangicTarihi"]);
                servis.BitisTarihi = Convert.ToDateTime(data["bitisTarihi"]);
                servis.DonusEklensinMi = true;
                servis.KalkisKod = varis[0];
                servis.KalkisHavalimani = varis[1];
                servis.KalkisSehir = varis[2];
                servis.KalkisUlke = varis[3];
                servis.KoltukLimiti = Convert.ToInt32(data["dkoltukLimiti"]);
                servis.LimiteBagliServisBedeli = Convert.ToDecimal(data["dlimiteBagliServis"]);
                servis.ServisBedeli = Convert.ToDecimal(data["dekstraServisBedeli"]);
                servis.Durum = true;
                if (data["tip"] == "İÇ HAT")
                {
                    servis.Tip = true;
                }
                else
                {
                    servis.Tip = false;
                }
                servis.VarisKod = kalkis[0];
                servis.VarisHavalimani = kalkis[1];
                servis.VarisSehir = kalkis[2];
                servis.VarisUlke = kalkis[3];
                entities.EkstraServis.Add(servis);
                entities.SaveChanges();
            }
            else
            {
                // Tek yön Ekstra Servis Bedeli ekleme
                servis.BaslangicTarihi = Convert.ToDateTime(data["baslangicTarihi"]);
                servis.BitisTarihi = Convert.ToDateTime(data["bitisTarihi"]);
                servis.DonusEklensinMi = false;
                servis.KalkisKod = kalkis[0];
                servis.KalkisHavalimani = kalkis[1];
                servis.KalkisSehir = kalkis[2];
                servis.KalkisUlke = kalkis[3];
                servis.KoltukLimiti = Convert.ToInt32(data["koltukLimiti"]);
                servis.LimiteBagliServisBedeli = Convert.ToDecimal(data["limiteBagliServis"]);
                servis.ServisBedeli = Convert.ToDecimal(data["ekstraServisBedeli"]);
                servis.Durum = true;
                if (data["tip"] == "İÇ HAT")
                {
                    servis.Tip = true;
                }
                else
                {
                    servis.Tip = false;
                }
                servis.VarisKod = varis[0];
                servis.VarisHavalimani = varis[1];
                servis.VarisSehir = varis[2];
                servis.VarisUlke = varis[3];

KeyifliBilet/Areas/Yonetim/Views/Panel/IletisimFormu.cshtml
@model KeyifliBilet.Areas.Yonetim.Models.IndexViewModel
@{
    ViewBag.Title = "IletisimFormu";
    Layout = "~/Areas/Yonetim/Views/Shared/MasterPage.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />

<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>

<section id="main-content">
    <section class="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">İletişim Formu web sitenizden gönderilen iletişim formu mesajları</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>

            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">

                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">

                                <table id="myTable" class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>Ziyaretçi</th>
                                            <th>Mail</th>
                                            <th>Telefon</th>
                                            <th>Mesaj</th>
                                            <th>Gönderim Tarihi</th>
                                            <th>Okunma Durumu</th>
                                            <th>Durum</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.iletisimFormu.Count() != 0)
                                        {
                                            foreach (var item in Model.iletisimFormu)
                                            {
                                                <tr class="odd gradeX" id="row_@item.IletisimId">
                                                    <td>@item.AdSoyad</td>
                                                    <td>@item.Mail</td>
                                                    <td>@item.Telefon</td>
                                                    <td>@item.Mesaj</td>
                                                    <td>@item.Tarih</td>
                                                    @if (item.Durum == true)
                                                    {
                                                        <td>
                                                            <span class="label label-sm label-success circle">Okundu</span>
                                                            AdminKeyifliBilet tarafından
                                                            <span class="label label-sm label-info circle">@item.OkunmaTarihi</span>
                                                            tarihinde okundu
                                                        </td>
                                                    }
                                                    else
                                                    {
                                                        <td>
                                                            <span class="label label-sm label-danger circle">Okunmadı</span>
                                                        </td>
                                                    }

                                                    <td class="center">
                                                        @if (item.Durum == true)
                                                        {
                                                            <a class="btn btn-success" href="@Url.Action("MesajDurum", "Panel", new
                                                                                            {
                                                                                                id = @item.IletisimId
                                                                                            })">Okunmadı olarak işaretle</a>
                                                        }
                                                        else
                                                        {
                                                            <a class="btn btn-danger" href="@Url.Action("MesajDurum", "Panel", new
                                                                                            {
                                                                                                id = @item.IletisimId
                                                                                            })">Okundu olarak işaretle</a>
                                                        }
                                                    </td>

                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <div class="alert alert-info">Mesaj bulunmamaktadır.</div>
                                        }
                                    </tbody>
                                </table>

                                <script>
                                    $('#myTable').DataTable();
                                </script>
                                <div class="pagination"></div>
                            </div>
                            <!-- /.table-responsive -->

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</section>

KeyifliBilet/Areas/Yonetim/Views/Panel/KutuGuncelle.cshtml
@model KeyifliBilet.Areas.Yonetim.Models.IndexViewModel
@foreach (var item in Model.kutu)
{
    <form id="myForm" action="@Url.Action("KutuDuzenle", "Panel",new { id = item.KutuId })" method="post" accept-charset="utf-8" enctype="multipart/form-data">
        <div id="listOfCustomers" style="height: 400px; overflow: auto;">

            <div class="portlet-title">
                <div class="caption">
                    <select class="form-control" id="kutuKategori" name="kutuKategori">
                        <option value="">Kategori Seçiniz</option>
                        @foreach (var data in Model.kutuKategori)
                        {
                            <option value="@data.KategoriId">@data+.Kategori</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label>KALKIŞ YERİ</label>
                <input class="form-control" type="text" name="kalkis" id="kalkis" value="@item.KalkisYeri" required="required">
            </div>
            <div class="form-group">
                <label>VARIŞ YERİ</label>
                <input class="form-control" type="text" name="varis" id="varis" value="@item.VarisYeri" required="required">
            </div>
            <div class="form-group">
                <label>GÖRSEL</label>
                <input class="form-control" type="file" name="resim" id="resim" placeholder="GÖRSEL" required="required">
            </div>

            <div class="box-footer">
                <button class="btn btn-xs btn-danger" id="btnSubmit" href="@Url.Action("KutuDuzenle", "Panel",new { id = item.KutuId })">
                    <span> EKLE</span>
                </button>
            </div>


        </div>


    </form>
}

KeyifliBilet/Areas/Yonetim/Views/Panel/ServisEkle.cshtml
<form id="myForm" action="@Url.Action("ServisEkle", "Panel")" method="post" accept-charset="utf-8" enctype="multipart/form-data">
    <div id="listOfCustomers" style="height: 600px; overflow: auto;">

        <div class="form-group">
            <label>Tip Seçiniz</label>
            <select name="tip" class="form-control">
                <option>İÇ HAT</option>
                <option>DIŞ HAT</option>

            </select>
        </div>
        <div class="form-group">
            <label>BAŞLANGIÇ TARİHİ</label>
            <input class="form-control" type="date" name="baslangicTarihi" placeholder="BAŞLANGIÇ TARİHİ" required="required">
        </div>
        <div class="form-group">
            <label>BİTİŞ TARİHİ</label>
            <input class="form-control" type="date" name="bitisTarihi" placeholder="BİTİŞ TARİHİ" required="required">
        </div>
        <div class="form-group">
            <label>KALKIŞ YERİ</label>
            <input class="form-control" name="kalkisYeri" id="kalkisYeri" autocomplete="off" placeholder="KALKIŞ YERİ" required="required" />

        </div>



        <div class="form-group">
            <label>VARIŞ YERİ</label>
            <input class="form-control" name="varisYeri" placeholder="VARIŞ YERİ" id="varisYeri" required="required">

        </div>

        <div class="form-group">
            <label>EKSTRA SERVİS BEDELİ </label>
            <input class="form-control" name="ekstraServisBedeli" id="ekstraServisBedeli" placeholder="EKSTRA SERVİS BEDELİİ" required="required">
        </div>
        <div class="form-group">
            <label>KOLTUK LİMİTİ</label>
            <input class="form-control" name="koltukLimiti" id="koltukLimiti" placeholder="KOLTUK LİMİTİ" required="required">
        </div>
        <div class="form-group">
            <label>LİMİTE BAĞLI SERVİS BEDELİ</label>
            <input class="form-control" name="limiteBagliServis" id="limiteBagliServis" placeholder="LİMİTE BAĞLI SERVİS BEDELİ" required="required">
        </div>

        <div class="form-group">
            <label>Dönüş Uçuşuda Eklensin mi?</label>
            <input class="form-control" type="checkbox" id="myCheck" name="myCheck" />
        </div>
        <div id="text" class="form-group">
            <label>DÖNÜŞ SERVİS BİLGİLERİ</label>

            <input class="form-control" name="dekstraServisBedeli" id="dekstraServisBedeli" placeholder="EKSTRA SERVİS BEDELİ" required="required">
            <input class="form-control" name="dkoltukLimiti" id="dkoltukLimiti" placeholder="KOLTUK LİMİTİ" required="required">
            <input class="form-control" name="dlimiteBagliServis" id="dlimiteBagliServis" placeholder="LİMİTE BAĞLI SERVİS BEDELİ" required="required">
        </div>
        <div class="box-footer">
            <button class="btn btn-xs btn-danger" id="btnSubmit" href="@Url.Action("ServisEkle", "Panel" )">
                <span> EKLE</span>
            </button>
        </div>


    </div>


</form>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script type="text/javascript">

    $("#kalkisYeri").keyup(function () {
        this.value = this.value.toUpperCase();
    });
    $("#varisYeri").keyup(function () {
        this.value = this.value.toUpperCase();
    });
    $(function () {

        $("#kalkisYeri,#varisYeri").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '/Panel/JsonGetir',
                    data: "{ 'term': '" + request.term + "'}",
                    dataType: "json",
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        response($.map(data, function (item) {

                            return item.label;

                        }))
                    },

                    error: function (response) {
                        alert(response.responseText);
                    }

                });
            },
            select: function (e, i) {
                var keyvalue = i.item.value;
            },
            minLength: 1
        });
        autofocus = true;
    });

</script>
@section js{

    <script>
        $(function () {


            var checkbox = $("#myCheck");
            var hidden = $("#text");

            hidden.hide();
            checkbox.change(function () {

                if (checkbox.is(':checked')) {

                    hidden.show();

                } else {

                    hidden.hide();


                }
            });
        });
    </script>
    <script>

        $(document).ready(function () {
            $("#ekstraServisBedeli").keyup(function (event) {
                $("#dekstraServisBedeli").val($(this).val());
            });
            $("#koltukLimiti").keyup(function (event) {
                $("#dkoltukLimiti").val($(this).val());
            });
            $("#limiteBagliServis").keyup(function (event) {
                $("#dlimiteBagliServis").val($(this).val());
            });

        });
    </script>
}

KeyifliBilet/Areas/Yonetim/Views/Panel/SinifEkle.cshtml
<form id="myForm" action="@Url.Action("SinifEkle", "Panel")" method="post" accept-charset="utf-8" enctype="multipart/form-data">
    <div id="listOfCustomers" style="height: 400px; overflow: auto;">


        <div class="form-group">
            <label>SINIF ADI</label>
            <input class="form-control" type="text" name="sinif" id="sinif" placeholder="SINIF ADI" required="required">
        </div>
        <div class="form-group">
            <label>SERVİS BEDELİ</label>
            <input class="form-control" type="text" name="servisBedeli" id="servisBedeli" placeholder="SERVİS BEDELİ" required="required">
        </div>



        <div class="box-footer">
            <button class="btn btn-xs btn-danger" id="btnSubmit" href="@Url.Action("SinifEkle", "Panel" )">
                <span> EKLE</span>
            </button>
        </div>


    </div>


</form>