KeyifliBilet/Models/ResultViewModel.cs
using KeyifliBilet.Iati_Models.Result;
using KeyifliBilet.Iati_Models.Search;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KeyifliBilet.Models
{
    public class ResultViewModel
    {
        public List<Result> Result { get; set; }
        public ViewSearch Search { get; set; }
        public List<Route> WeekSearch { get; set; }
        public DestinationSearch DestinationSearch { get; set; }
    }
}

KeyifliBilet/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KeyifliBilet.Models
{
    public class Search
    {
        public bool IsOneWay { get; set; }
        public string DEP_Airport_Code { get; set; }
        public string DEP_Airport_Name { get; set; }
        public string DEP_Airport_CityName { get; set; }
        public bool DEP_Airport_IsCity { get; set; } // allinFromCity
        public string DepartureDate { get; set; }
        public string ARR_Airport_Code { get; set; }
        public string ARR_Airport_Name { get; set; }
        public string ARR_Airport_CityName { get; set; }
        public bool ARR_Airport_IsCity { get; set; }
        public string ReturnDate { get; set; }
        public int Adult { get; set; }
        public int Child { get; set; }
        public int Infant { get; set; }
        public int Total { get; set; }
        public string CabinClass { get; set; }
        public bool NoStop { get; set; }
    }
}

KeyifliBilet/Controllers/FlightController.cs
using KeyifliBilet.Areas.Yonetim.Models;
using KeyifliBilet.Iati.Enums;
using KeyifliBilet.Iati.Request;
using KeyifliBilet.Iati.Response;
using KeyifliBilet.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace KeyifliBilet.Controllers
{
    public class FlightController : Controller
    {
        static FlightResponse list;
        //static List<Route> data;
        static List<Iati.Response.FlightResponse> selectedflights;
        static ViewSearch ViewSearch;
        KeyifliBiletEntities entities = new KeyifliBiletEntities();
        IndexViewModel vm = new IndexViewModel();
        public ActionResult RT()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Result(ViewSearch model)
        {
            var bt = System.Convert.ToDateTime(Convert.ToDateTime(model.DepartureDate).ToString("yyyy-MM-dd 00:00:00.000"));
            var kt = System.Convert.ToDateTime(Convert.ToDateTime(model.ReturnDate).ToString("yyyy-MM-dd 00:00:00.000"));

            decimal? agencyCommission = 0;

            var extraservicedep = entities.EkstraServis.Where(
                x => x.BaslangicTarihi <= bt &&
                x.BitisTarihi >= kt &&
                x.KalkisKod == model.DEP_Airport_Code &&
                x.VarisKod == model.ARR_Airport_Code
                ).Select(c => c).ToList().OrderByDescending(x => x.Id).FirstOrDefault();
            var promo = entities.Siniflar.Where(x => x.SinifAdi == "PROMO").Select(w => w.ServisBedeli).FirstOrDefault();
            var economy = entities.Siniflar.Where(x => x.SinifAdi == "ECONOMY").Select(w => w.ServisBedeli).FirstOrDefault();
            var business = entities.Siniflar.Where(x => x.SinifAdi == "BUSINESS").Select(w => w.ServisBedeli).FirstOrDefault();

            selectedflights = new List<FlightResponse>();
            ViewSearch = model;

            if (Convert.ToDateTime(model.DepartureDate) > Convert.ToDateTime(model.ReturnDate))
            {
                model.ReturnDate = model.DepartureDate;
            }
            var flight = new Iati.Request.FlightRequest()
            {
                adult = model.Adult.ToString(),
                allinFromCity = model.DEP_Airport_IsCity,
                allinToCity = model.ARR_Airport_IsCity,
                child = model.Child.ToString(),
                cip = false,
                classType = model.CabinClass == "ALL" ? null : (Iati.Enums.ClassType?)Enum.Parse(typeof(Iati.Enums.ClassType), model.CabinClass),
                currency = Iati.Enums.Currency.TL,
                fromAirport = model.DEP_Airport_Code,
                fromDate = Convert.ToDateTime(model.DepartureDate).ToString("yyyy-MM-dd"),
                getBaggageInfo = false,
                infant = model.Infant.ToString(),
                returnDate = model.IsOneWay ? "" : Convert.ToDateTime(model.ReturnDate).ToString("yyyy-MM-dd"),
                toAirport = model.ARR_Airport_Code,
                usePersonFares = true
            };
            var flights = await Iati.Search.GetFlights(flight);
            //test
            //  var data = flights.result.flights.Where(w => w.testInfo.suitableForTest == true && w.fares.Where(f => f.freeSeatCount > 0).Count() >= 0).ToList();
            //prod

            var data = flights.result.flights.ToList();
            foreach (var ff in selectedflights)
            {
                foreach (var item in ff.result.flights)
                {
                    foreach (var fa in item.fares)
                    {
                        foreach (var pf in fa.personFares)
                        {
                            if (extraservicedep == null)
                            {
                                if (fa.type == "PROMO")
                                {
                                    pf.agencyCommission = Convert.ToDouble(promo);
                                }
                                if (fa.type == "ECONOMY")
                                {
                                    pf.agencyCommission = Convert.ToDouble(economy);

                                }
                                if (fa.type == "BUSINESS")
                                {
                                    pf.agencyCommission = Convert.ToDouble(business);
                                }
                            }
                            else if (extraservicedep != null && fa.freeSeatCount <= extraservicedep.KoltukLimiti)
                            {
                                pf.agencyCommission = Convert.ToDouble(extraservicedep.ServisBedeli);
                            }
                            else
                            {
                                pf.agencyCommission = extraservicedep.ServisBedeli == null ? 0 : Convert.ToDouble(extraservicedep.ServisBedeli);
                            }
                        }
                    }
                }
            }

            foreach (var f in data.Where(x => x.providerKey == "Pegasus" && x.pricingType == "FREE_FORM").ToList())
            {

                foreach (var fare in f.fares)
                {
                    if (model.Infant == 0)
                    {
                        fare.personFares.ToList().Where(p => p.passangerType == "INFANT").ToList().ForEach(x => fare.personFares.Remove(x));
                    }
                    if (model.Adult == 0)
                    {
                        fare.personFares.ToList().Where(p => p.passangerType == "ADULT").ToList().ForEach(x => fare.personFares.Remove(x));
                    }
                    if (model.Child == 0)
                    {
                        fare.personFares.ToList().Where(p => p.passangerType == "CHILD").ToList().ForEach(x => fare.personFares.Remove(x));
                    }

                    foreach (var pf in fare.personFares)
                    {
                        //pf.agencyCommission = (pf.agencyCommission / 3) * (model.Adult + model.Child * model.Infant);
                        if (pf.passangerType == "INFANT")
                        {
                            pf.serviceFee = pf.serviceFee * model.Infant;
                            pf.supplement = pf.supplement * model.Infant;
                            pf.tax = pf.tax * model.Infant;
                            pf.total = pf.total * model.Infant;

                            pf.agencyCommission = pf.agencyCommission * model.Infant;

                        }
                        if (pf.passangerType == "ADULT")
                        {
                            pf.serviceFee = pf.serviceFee * model.Adult;
                            pf.supplement = pf.supplement * model.Adult;
                            pf.tax = pf.tax * model.Adult;
                            pf.total = pf.total * model.Adult;
                            pf.agencyCommission = pf.agencyCommission * model.Adult;
                        }
                        if (pf.passangerType == "CHILD")
                        {
                            pf.serviceFee = pf.serviceFee * model.Child;
                            pf.supplement = pf.supplement * model.Child;
                            pf.tax = pf.tax * model.Child;
                            pf.total = pf.total * model.Child;
                            pf.agencyCommission = pf.agencyCommission * model.Child;
                        }

                    }
                }
            }
            if (model.IsOneWay == false)
            {
                foreach (var d in data.Where(x => x.providerKey.Contains("Galileo") || x.providerKey.Contains("Amadeus") || x.providerKey.Contains("Sabre")).ToList())
                {
                    foreach (var fa in d.fares)
                    {
                        foreach (var pf in fa.personFares)
                        {
                            pf.total = pf.total / 2;
                            if (extraservicedep == null)
                            {
                                if (fa.type == "PROMO")
                                {
                                    pf.agencyCommission = Convert.ToDouble(promo);
                                }
                                if (fa.type == "ECONOMY")
                                {
                                    pf.agencyCommission = Convert.ToDouble(economy);

                                }
                                if (fa.type == "BUSINESS")
                                {
                                    pf.agencyCommission = Convert.ToDouble(business);
                                }
                            }
                            else if (extraservicedep != null && fa.freeSeatCount <= extraservicedep.KoltukLimiti)
                            {
                                pf.agencyCommission = Convert.ToDouble(extraservicedep.ServisBedeli);
                            }

                        }
                    }
                }
            }
            else
            {
                foreach (var d in data.Where(x => x.providerKey.Contains("Galileo") || x.providerKey.Contains("Amadeus") || x.providerKey.Contains("Sabre")).ToList())
                {
                    foreach (var fa in d.fares)
                    {
                        foreach (var pf in fa.personFares)
                        {

                            if (extraservicedep == null)
                            {
                                if (fa.type == "PROMO")
                                {

KeyifliBilet/Views/Flight/BankInfo.cshtml
@{
    ViewBag.Title = "BankInfo";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@Html.Action("HeaderIndex", "Home")
<section class="flights-list flight-information mt-sm-5 mt-5 pt-sm-5">
    <div class="container mt-sm-5 ">
        <div class="row mt-sm-3">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-head">

                            <div role="alert">
                                <strong style="display: block;padding-bottom: 10px;font-size: 18px;">
                                    Bir hata oluştu
                                </strong>
                                <ul>
                                    <li><strong>Banka Hatası</strong></li>
                                    <li><i class="fa fa-angle-right"></i> Ödemeniz kartınızdan çekilemedi</li>
                                    <li><i class="fa fa-angle-right"></i> @ViewBag.Message</li>
                                </ul>
                                <br><br>
                                <a href="@Url.Action("Index","Home")" class="btn btn btn-primary">
                                    <i class="fa fa-angle-double-left"></i>
                                   Ana Sayfaya Dön
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="yourContainer"></div>
@Html.Action("Footer", "Home")

KeyifliBilet/Views/Flight/CardInfo.cshtml
<div class="row clearfix">
    <div class="col-lg-6">
        <h3 class="size-14 mb-sm-1">Ödeme Bilgileri</h3>
    </div>
    <div class="col-lg-6">
    </div>
</div>
<div class="row clearfix">
    <div class="col-lg-6">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="control-label">Kart Üzerindeki İsim</label>
                <input class="form-control" data-val="true" data-val-required="Kart üzerindeki isim soyisim bilgisini giriniz !" id="PaymentForm_CardNameSurname" name="PaymentForm.CardNameSurname" placeholder="Kart üzerindeki isim soyisim" type="text" value="">
                <span class="field-validation-valid" data-valmsg-for="PaymentForm.CardNameSurname" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Kredi Kartı Numarası</label>
                <input class="form-control" data-val="true" data-val-required="Kart numarasını giriniz !" id="PaymentForm_CardNumber" name="PaymentForm.CardNumber" placeholder="Kart numarası" type="text" value="">
                <span class="field-validation-valid" data-valmsg-for="PaymentForm.CardNumber" data-valmsg-replace="true"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label class="control-label">Ay</label>
                <select class="form-control" data-val="true" data-val-required="Son kullanma tarihi ay seçiniz !" id="PaymentForm_CardMonth" name="PaymentForm.CardMonth">
                    <option value="01">01 - Ocak</option>
                    <option value="02">02 - Şubat</option>
                    <option value="03">03 - Mart</option>
                    <option value="04">04 - Nisan</option>
                    <option value="05">05 - Mayıs</option>
                    <option value="06">06 - Haziran</option>
                    <option value="07">07 - Temmuz</option>
                    <option value="08">08 - Ağustos</option>
                    <option value="09">09 - Eylül</option>
                    <option value="10">10 - Ekim</option>
                    <option value="11">11 - Kasım</option>
                    <option value="12">12 - Aralık</option>
                </select>
                <span class="field-validation-valid" data-valmsg-for="PaymentForm.CardMonth" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group col-md-4">
                <label class="control-label">Yıl</label>
                <select class="form-control" data-val="true" data-val-required="Son kullanma tarihi yıl seçiniz !" id="PaymentForm_CardYear" name="PaymentForm.CardYear">
                    <option value="18">2018</option>
                    <option value="19">2019</option>
                    <option value="20">2020</option>
                    <option value="21">2021</option>
                    <option value="22">2022</option>
                    <option value="23">2023</option>
                    <option value="24">2024</option>
                    <option value="25">2025</option>
                    <option value="26">2026</option>
                    <option value="27">2027</option>
                </select>
                <span class="field-validation-valid" data-valmsg-for="PaymentForm.CardYear" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group col-md-4">
                <label class="control-label">Cvv</label>
                <input autocomplete="Off" class="form-control col-md-6" data-val="true" data-val-required="Kart güvenlik numarasını giriniz !" id="PaymentForm_CardCVV" name="PaymentForm.CardCVV" type="text" value="">
                <span class="field-validation-valid" data-valmsg-for="PaymentForm.CardCVV" data-valmsg-replace="true"></span>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
    </div>
</div>

KeyifliBilet/Views/Flight/FareDetails.cshtml
@model List<KeyifliBilet.Iati.Response.Flight>
@foreach (var flight in Model)
{
<div class="row mt-sm-3">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-head">
                    <i class="flaticon-transport"></i> <strong>@flight.legs[0].arrivalCityName</strong>, <nobr>@flight.legs[0].localDepartureDate</nobr>
                </div>
            </div>
            <div class="flight-itinerary departure">
                <div class="airlines">
                    <div class="content">
                        <span class="icon-carrier-@flight.legs[0].departureAirport"></span>
                        <span class="title">@flight.legs[0].flightNo</span>
                    </div>
                </div>
                <div class="departure col-sm-2 col-xs-3 col-sm-push-0 col-xs-push-2">
                    <div class="content">
                        <div class="time">@flight.legs[0].departureTime.ToShortTimeString()</div>
                        <div class="airport">@flight.legs[0].departureAirport</div>
                    </div>
                </div>
                <div class="stops col-sm-1 col-xs-4 col-sm-push-0 col-xs-push-2">
                    <div class="content">
                        <div class="date">@flight.legs[0].legDurationMinute d</div>
                        <div class="airport">
                            <div class="stop">
                                <div class="stop-row">DİREKT</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="arrival col-sm-2 col-xs-3 col-sm-push-0 col-xs-push-2">
                    <div class="content">
                        <div class="time">@flight.legs[0].arrivalTime.ToShortTimeString()</div>
                        <div class="airport">@flight.legs[0].arrivalAirport</div>
                    </div>
                </div>
                <div class="col-sm-5"></div><div class="pricing col-sm-2 col-xs-4">
                    <div class="content">
                        <div class="price">
                            <strong class="amount">
                                @flight.fares[0].totalSingleAdultFare.ToString().Split(',')[0]<span class="sup">
                                    '
                                    @if (flight.fares[0].totalSingleAdultFare.ToString().IndexOf(',') > 0)
                                    {
                                        @flight.fares[0].totalSingleAdultFare.ToString().Split(',')[1]
                                    }
                                    else
                                    {
                                        <span>00</span>
                                    }
                                    <span class="desc">@flight.fares[0].currency</span>
                                </span>
                            </strong>
                        </div>
                        <div class="per-person">vergi dahil </div>
                    </div>
                </div>
            </div>

        </div>

        <section class="section noborder nopadding sticky-wrapper mb-5" id="sticky-wrapper">
            <div class="container container-gray" id="pricebreakdownscroll">
                <div class="row grid-mbl mt-5">
                    <div class="col-6 pr-0-mbl">
                        <h2 class="nomargin size-20 weight-300">Toplam tutar</h2>
                    </div>
                    <div class="col-6 pl-0-mbl text-right">
                        <h2 class="bold nomargin text-right blue-light weight-500 size-30">
                            <span><span class="price-currency">@flight.fares[0].currency</span><span>@flight.fares[0].totalSingleAdultFare</span></span>
                        </h2>
                        <span class="text-muted size-11">VERGİ VE TAŞIYICI ÜCRETLERİ DAHİL</span>
                    </div>
                </div>
                <div class="row mt-3 mb-3">
                    <div class="col-12 red mb-15">
                        <a class="size-16 weight-500" style="color: #f37321;" data-toggle="collapse" data-target="#collapse-10" aria-expanded="false" aria-controls="collapse-10">
                            <span>Ücret detaylarını göster</span>
                            <i class="fa fa-chevron-right red ml-1"></i>
                        </a>
                    </div>
                </div>
                <div class="row mt-1 collapse" id="collapse-10">
                    <div class="col-12">
                        <ul class="calculated-price-list fs-14">
                            <li>
                                <span>1 Yetişkin</span>
                                <span class="pull-right">
                                    <span class="price-column-currency">@flight.fares[0].currency</span>
                                    <span>@flight.fares[0].totalSingleAdultFare</span>
                                </span>
                            </li>
                            <li class="mb-10"></li>
                            <li>
                                <a class="black">
                                    <u><span>Vergi ve diğer harçlar</span></u>
                                </a>
                                <span class="pull-right">
                                    <span class="price-column-currency">@flight.fares[0].currency</span>
                                    <span>@flight.fares[0].personFares[0].tax</span>
                                </span>
                            </li>
                            <li>
                                <a class="black">
                                    <u><span>Biletleme servis ücreti</span></u>
                                </a>
                                <span class="pull-right">
                                    <span class="price-column-currency">@flight.fares[0].currency</span>
                                    <span>@flight.fares[0].personFares[0].serviceFee</span>
                                </span>
                            </li>


                        </ul>
                    </div>
                </div>
            </div>
        </section>

    </div>
</div>



}

KeyifliBilet/Views/Flight/HeaderResult.cshtml
<header class="cd-header">
    <div id="cd-logo"><a href="/"><img src="/Content/assets/images/logo.png" alt="Adaş Turizm"></a></div>


    <nav class="hidden-xs">
        <ol class="keyifli-breadcrumb triangle custom-icons">
            <li class="current"><a><i class="flaticon-transport"></i> UÇUŞ SEÇİMİ</a></li>
            <li><a><i class="flaticon-people-1"></i> YOLCU BİLGİLERİ</a></li>
            <li><em><i class="flaticon-commerce"></i> ÖDEME</em></li>
        </ol>
    </nav>

    <nav class="cd-main-nav">
        <ul>
            <li><a href="/tr/iptal-iade">İptal / İade</a></li>
            <li class="divider"></li>
            <li><a href="/tr/online-check-in">Online Check-In</a></li>
            <li class="divider"></li>
            <li><a href="/tr/iletisim">İletişim</a></li>
            <li class="right dropdown">
                <a class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">TR</a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">EN</a>
                </div>
            </li>
            <li class="right"><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="login" class="btnMember"><i class="icon-user"></i> Giriş Yap</a></li>
            <li class="divider right"></li>
            <li class="right"><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="register" class="btnMember">Üye Ol</a></li>
            <li class="divider right"></li>
            <li class="right phone"><a href="tel://08505504114 "><i class="icon-phone3"></i> 0850 550 41 14</a></li>

        </ul>
    </nav>

    <a href="#" data-toggle="modal" data-target=".bs-example-modal-sm" tabcontent="login" class="btnMember visible-xs"><i class="icon-user"></i> Giriş Yap</a>
</header>

KeyifliBilet/Views/Flight/RT.cshtml
@{
    ViewBag.Title = "RT";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}


@Html.Action("HeaderResult", "Flight")
<input id="hdnHidePreviousDay" name="hdnHidePreviousDay" type="hidden" value="False">
<section id="adas-result" class="hidden-xs">
    <div id="adas-result-background"></div>
    <div id="adas-result-tagline">
        <div class="container">
            <div class="search-engine">
                <div class="search-engine-steps">
                    <div class="engine-step" id="tabQuickFlights">
                        <input id="hdnIsOneWay" name="hdnIsOneWay" type="hidden" value="true">
                        @Html.Action("PartialSearch", "Home")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="mobile-backhead visible-xs">
    <a class="btn btn-link" href="/"><span class="fa fa-angle-left"></span><span class="sr-only"> Uçuş Seçimi</span> Uçuş Seçimi</a>
</section>
@Html.Action("FilterOneWay", "Flight")
@Html.Action("Departure", "Flight")
@Html.Action("Arrival", "Flight")
@section js{
    <script src="~/Content/assets/js/scripts.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#adas-home-tagline").sticky({ topSpacing: 0 });
            $('#layerslider').layerSlider({ skin: 'noskin', skinsPath: 'Content/assets/plugins/slider.layerslider/skins/', pauseOnHover: false, navButtons: true, slideDirection: 'top' });
            WDT.SearchBox.CreateBox();
            WDT.SearchPnr.Init();
            WDT.Member.LoginRequired();
        });</script>
    <script type="text/javascript">
        $(document).ready(function () {
            WDT.Member.Init();
        });</script>
}
<script>
    function selectFlight(supplier, groupId, isDomestic, flightId, isreturn, itemId) {
        var depOrArr = isreturn == "true" ? 0 : 1;
        if (isDomestic == "true") {
            $(".asItem[data-fid!='" + flightId + "'][data-is-dep='" + depOrArr + "']").hide();
            $(".asItem[data-fid='" + flightId + "'][data-is-dep='" + depOrArr + "']").show();
        } else {
            if (groupId != "" | groupId != undefined && supplier == "Galileo") {
                $(".asItem[data-supplier='" + supplier + "'][data-grp='" + groupId + "']").show();
                $(".asItem[data-supplier='" + supplier + "'][data-grp!='" + groupId + "']").hide();
            }
            else {

            }
        }
        if (depOrArr == "1") {
            $(document).find("input[name='departure'").val(flightId);

        } else {
            $(document).find("input[name='arrival'").val(flightId);
        }
        $("a[id='" + itemId + "']").addClass("selectedflight");
        var selectedFlight = $("a.selectedflight").length;
        var isRt = $(".asItem[data-is-dep='0']").length > 0 ? true : false;
        if (isRt) {
            if (selectedFlight == 2) {

                loadFlightPrice();
            }
        } else {
            loadFlightPrice();
        }
    }
</script>

KeyifliBilet/Views/Flight/Search.cshtml
@model KeyifliBilet.Models.Flight
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}